#!/bin/bash
if [ -z "$1" ]
  then
    echo "This script requires one argument, the absolute path of the CSV input file."
	exit 0
fi
JAVA_HOME=/usr/java/jdk1.7.0_03
CLASSPATH=/home/mholtom/workspace/kontagent/target/classes
$JAVA_HOME/bin/java -cp $CLASSPATH com/kontagent/MatrixRPNCalculator $1
exit 0
